### PR TITLE
Correcting HTML.

### PR DESCRIPTION
**Pull request by aomarks**

### CODE REVIEW

**Comment by aomarks** [comment]
Ping this is blocking me.

**Comment by VoidingWarranties** [comment]
https://web.archive.org/web/20070319162801/http://www.sewingandembroiderywarehouse.com/embtrb.htm

**Comment by VoidingWarranties** [comment]
After further consideration I’m unsure if the original code without the closing tag was ever incorrect.

According to the HTML spec in section [13.1.2.4 Optional tags](https://html.spec.whatwg.org/multipage/syntax.html#optional-tags):
> An [html](https://html.spec.whatwg.org/multipage/semantics.html#the-html-element) element's [end tag](https://html.spec.whatwg.org/multipage/syntax.html#syntax-end-tag) may be omitted if the [html](https://html.spec.whatwg.org/multipage/semantics.html#the-html-element) element is not immediately followed by a [comment](https://html.spec.whatwg.org/multipage/syntax.html#syntax-comments).

I propose reverting this change in order to reduce the size of this HTML page by 8 bytes. 

@aomarks what are your thoughts?

**Comment by VoidingWarranties** [comment]
Friendly ping @aomarks 

Reverting this change should help keep our bandwidth costs down.

**Pull request merged**
